export const actions = {
    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    GET_TRANSACTIONS: 'GET_TRANSACTIONS',
    GET_TRANSACTIONS_ERROR: 'GET_TRANSACTIONS_ERROR'
}
